stalks:
  build: .
  ports:
   - "15000:8000"
  links:
   - mysql
  environment:
    STALKS_DB_HOST: mysql
    STALKS_DB_PASS: stalker
    STALKS_DB_USER: stalker
    STALKS_DB_PORT: 3306
    STALKS_DB_NAME: stalk
    
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: test
    MYSQL_DATABASE: stalk
    MYSQL_USER: stalker
    MYSQL_PASSWORD: stalker
